USE test;
DROP TABLE IF EXISTS book;
CREATE TABLE book(
 id INT NOT NULL AUTO_INCREMENT
 , title VARCHAR(100) NOT NULL
 , description VARCHAR(255) NOT NULL
 , author VARCHAR(100) NOT NULL
 , isbn VARCHAR(20) NOT NULL
 , printYear INT NOT NULL
 , readAlready TINYINT(1) NOT NULL
, PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
INSERT INTO book (id, title, description, author, isbn, printYear, readAlready) 
VALUES (1, 
"The Book of Dust: Volume One: La Belle Sauvage", 
"Eleven-year-old Malcolm Polstead and his demon, Asta, live with his parents at the Trout Inn near Oxford. Across the River Thames  is the Godstow Priory where the nuns",
"Philip Pullman",
9780385604413,
2017,
false),
(2, 
"Beneath a Scarlet Sky: A Novel",
"What makes a hero? If you are Pino Lella, the protagonist in Mark Sullivan’s riveting World War II thriller, you risk everything to save as many souls as you can by sneaking them over the Swiss Alps to safety.",
"Kindle Edition",
0135601913,
2017,
false
),
(3, 
"Mind Over Matter: A Passionate and Intriguing Novel of Suspense",
"David Brady needs a star for his documentary on paranormal psychology. When he finds out theatrical agent A.J. Fields has a psychic for a client, he’s thrilled. However, A.J. is reluctant to let her client work with the smooth-talking producer",
"Nora Roberts",
0255401913,
2017,
false
),
(4, 
"Harry Potter and the Sorcerer's Stone",
"Turning the envelope over, his hand trembling, Harry saw a purple wax seal bearing a coat of arms; a lion, an eagle, a badger and a snake surrounding a large letter 'H'.",
"J.K. Rowling",
0195445313,
2015,
false
),
(5, 
"Pitseolak: PICTURES OUT OF MY LIFE",
"Hard Cover. Near Fine in a Very Good+ Dustjacket. Edited from tape-recorded interviews by Dorothy Eber. 95 pages, cloth. Story of the life of this Eskimo artist growing up in the Arctic.",
"Pitseolak and Eber, Dorothy Eber",
0195401913,
1971,
false
),
(6, 
"Pride and Prejudice",
"Pride and Prejudice has delighted generations of readers with its unforgettable cast of characters, carefully choreographed plot, and a hugely entertaining view of the world and its absurdities. ",
"Jane Austen",
0199535566,
2008,
false
),
(7, 
"Persuasion",
"Persuasion celebrates romantic constancy in an era of turbulent change. Written as the Napoleonic Wars were ending, the novel examines how a woman can at once remain faithful to her past and still move forward into the future.",
"Jane Austen",
0199535558,
2008,
false
),
(8, 
"Emma",
"So speculate the friends and neighbours of Emma Woodhouse, the lovely, lively, wilful,and fallible heroine of Jane Austen's fourth published novel.",
"Jane Austen",
0199535523,
2008,
false
),
(9, 
"Dubliners",
"Although James Joyce began these stories of Dublin life in 1904, when he was 22, and had completed them by the end of 1907, they remained unpublished until 1914 — victims of Edwardian squeamishness",
"James Joyce",
0486268705,
1991,
false
),
(10, 
"Dr. Faustus (Dover Thrift Editions)",
"One of the most durable myths in Western culture, the story of Faust tells of a learned German doctor who sells his soul to the devil in exchange for knowledge and power.",
"Christopher Marlowe",
0486282082,
1994,
false
),
(11, 
"English Romantic Poetry: An Anthology",
"Encompassing a broad range of subjects, styles, and moods, English poetry of the late eighteenth and early nineteenth centuries is generally classified under the term Romantic, suggesting an emphasis on imagination and individual experience",
"William Blake; William Wordsworth; Samuel Taylor Coleridge; Lord Byron; Percy Bysshe Shelley",
0486292827,
1996,
false
),
(12, 
"The Count of Monte Cristo",
"Alexandre Dumas",
"Pitseolak and Eber, Dorothy Eber",
0451529707,
2005,
false
),
(13, 
"The Story of King Arthur and His Knights",
"In these wonderfully illustrated tales, renowned storyteller Howard Pyle carries us back to the enchanting world of King Arthur and his Round Table. ",
"Howard Pyle",
0451530241,
2006,
false
),
(14, 
"The Fallacy Detective: Thirty-Eight Lessons on How to Recognize Bad Reasoning",
"WORKBOOK EDITION: Includes spaces for readers to write in their answers to the exercises. What is a fallacy? A fallacy is an error in logic a place where someone has made a mistake in his thinking. ",
"Nathaniel Bluedorn; Hans Bluedorn",
0974531575,
2015,
false
),
(15, 
"Henle Latin First Year",
"Thorough mastery of forms, basic syntax, and simple vocabulary are primary objectives of Henle Latin First Year that enable students to handle simple readings and translations. ",
"Robert J. Henle",
0829410260,
1958,
false
),
(16, 
"Seasons. Months. Days of The Week",
"Seasons. Months. Days of The Week.",
"Main Reed",
9785811224579,
2014,
false
),
(17, 
"It Couldn't Just Happen: Knowing the Truth About God's Awesome Creation",
"This four-color, Gold Medallion Book Award winner is a perfect tool that offers solid, biblical answers to some of the tough questions kids ask about evolution and our world.",
"Lawrence O. Richards",
1400317142,
2011,
false
),
(18, 
"Carry On, Mr. Bowditch",
"Indentured at age twelve. Nathaniel Bowditch would spend the next nine years at sea.",
"Esther Wood Brady",
059045577,
2000,
false
),
(19, 
"Crispin: The Cross of Lead",
"Avi's plot is engineered for maximum thrills, with twists, turns, and treachery aplenty. . . . A page-turner to delight Avi's fans, it will leave readers hoping for a sequel.-Publishers Weekly (starred review)",
"Avi",
0786816589,
2004,
false
),
(20, 
"The Bronze Bow",
"He trains my hands for war, so that my arms can bend a bow of bronze. –from the Song of David (2 Samuel 22:35)The Bronze Bow, written by Elizabeth George Speare",
"Elizabeth George Speare",
0395137195,
1997,
false
),
(21, 
"A Gathering of Days",
"The journal of a fourteen-year-old girl, kept the last year she lived on the family farm, records daily events in her small New Hampshire town",
"Joan W. Blos",
0439793769,
2005,
false
),
(22, 
"Number the Stars",
"Ten-year-old Annemarie Johansen and her best friend Ellen Rosen often think of life before the war.",
"Lois Lowry",
0440227534,
1998,
false
);